db.scrapedData.insert([{
  "url" : "https://www.allrecipes.com/recipe/75490/shrimp-and-sugar-snap-peas/",
  "title" : "Shrimp and Sugar Snap Peas",
  "blogLogo" : "https://secureimages.allrecipes.com/ar-images/ARlogo.svg",
  "desc" : "Quick and easy pasta dish with a little bite that will make anyone look like a gourmet chef. Adjust the chili oil to your own spice level.",
  "rating" : "4.0087718963623",
  "numOfRatings" : "77 reviews",
  "prepTime" : "20",
  "cookTime" : "10",
  "readyIn" : "30",
  "step0" : "Bring a large pot of lightly salted water to a boil. Add linguini pasta, and cook for 8 to 10 minutes or until al dente. Drain, reserving 1/4 cup liquid.",
  "step1" : "Heat the olive oil and chili oil in a wok over medium-high heat. Mix in the shrimp, pea pods, and garlic. Cook and stir 2 minutes, until shrimp are almost opaque. Remove from heat, and set aside.",
  "step2" : "Pour the wine into the wok, and bring to a boil. Cook until reduced by 1/3. Return shrimp, peas, and garlic to the wok, and stir in the reserved pasta water. Continue to cook and stir until shrimp are opaque. Remove wok from heat, and mix in the butter, lemon juice, and basil. Toss with the cooked pasta to serve.",
  "step3" : "",
  "step4" : "",
  "step5" : "",
  "step6" : "",
  "calories" : "403 calories;",
  "fat" : "7.7",
  "carbs" : "47.1",
  "protein" : "25.5",
  "cholesterol" : "133",
  "sodium" : "130",
  "ingredients" : "1 (16 ounce) package uncooked linguini pasta, 2 tablespoons olive oil, 1 teaspoon chili oil, 1 1/2 pounds medium shrimp, peeled and deveined, 1 pound sugar snap pea pods, 2 large cloves garlic, minced, 1 1/2 cups dry white wine, 1/4 cup reserved pasta water, 1 tablespoon unsalted butter, 1 tablespoon fresh lemon juice, 1/3 cup chopped fresh basil" 
}])
